---
title: "EDA User Define Function"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 사용자 정의함수


### 인수설정 & 미정의 인수 설정

```{r }
hello.person<-function(first,last="Doe",...){
  print(sprintf("hello,%s %s!",first,last))
}

hello.person("AVB","lander",extra="Good bye")
hello.person("BDC","lander","Good morning")
```

### 자동화 사용


```{r}
# do.call함수의 이용
do.call(hello.person,args=list(first="AAA",last="BBB"))

# 학생 명부 데이터 생성
f.name <- c("John", "Ang", "Bull", "David", "Janice", 
            "Cheryl", "Reuven", "Greg", "Joel", "Mary")
l.name <- c("Da", "ela", "winkle", "Jones", "Markhammer",
            "Cushing", "Ytzrhak", "Knox", "England", "Rayburn")
math <- c(502, 600, 412, 358, 495, 512, 410, 625, 573, 522)
science <- c(95, 99, 80, 82, 75, 85, 80, 95, 89, 86)
english <- c(25, 22, 18, 15, 20, 28, 15, 30, 27, 18)
roster <- data.frame(f.name, l.name, math, science, english, 
                     stringsAsFactors=FALSE)
roster

# do.call이용한 자동반복 시행
do.call(hello.person, 
        args = list(first = roster$f.name, 
                    last = roster$l.name))
# 일련의 데이터와 원하는 R함수를 인수값으로 입력하면 계산이 되도록 
calc <- function(x, func = mean) {
  do.call(func, args = list(x))
}

calc(1:10)
calc(1:10, mean)
calc(1:10, sum)
calc(1:10, sd)

```


